### ISSUE TITLE
node-dev path breaks in npm 3

### ISSUE THREAD

**Issue by redbugz** [camshaft/startup#12]
When using Node 5 and npm 3, the relative path to node-dev breaks because node-dev has been flattened

```
21:27:46 web.1  | Error: spawn /src/app/node_modules/startup/node_modules/.bin/node-dev ENOENT
21:27:46 web.1  |     at exports._errnoException (util.js:860:11)
21:27:46 web.1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
21:27:46 web.1  |     at onErrorNT (internal/child_process.js:344:16)
21:27:46 web.1  |     at doNTCallback2 (node.js:450:9)
21:27:46 web.1  |     at process._tickCallback (node.js:364:17)
21:27:46 web.1  |     at Function.Module.runMain (module.js:459:11)
21:27:46 web.1  |     at startup (node.js:136:18)
21:27:46 web.1  |     at node.js:972:3
21:27:46 web.1  | exited with code 1
21:27:46 system | sending SIGTERM to all processes
```

**Comment by camshaft** [comment]
fixed in da853fca438e4b38f0e9b6c0bd15a87744985196
